//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesFirstTranslations.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissingTranslationsView
    {
        public string Culture { get; set; }
        public int FK_BranchId { get; set; }
        public Nullable<int> MissingTranslations { get; set; }
    }
}
