//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesFirstTranslations.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RftContext : DbContext
    {
        public RftContext()
            : base("name=RftContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BranchResourceFile> BranchResourceFiles { get; set; }
        public virtual DbSet<ResourceFile> ResourceFiles { get; set; }
        public virtual DbSet<ResourceString> ResourceStrings { get; set; }
        public virtual DbSet<Translation> Translations { get; set; }
        public virtual DbSet<TranslationsAllBranchesView> TranslationAllBranches { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<TranslationsJoinedResourceStringsView> TranslationsJoinedResourceStringsViews { get; set; }
        public virtual DbSet<MissingTranslationsView> MissingTranslationsViews { get; set; }
        public virtual DbSet<BranchResourceFilesView> BranchResourceFilesViews { get; set; }
    
        public virtual ObjectResult<AllTranslationsForResource> GetAllTranslationsForResource(string doc)
        {
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllTranslationsForResource>("GetAllTranslationsForResource", docParameter);
        }
    }
}
